### PR TITLE
Test showing an issue when mapping if a type has been explicitly defined

### PR DESCRIPTION
**Pull request by kentongray**
Wanted to create a simple test case to show the exception and see if you have any ideas. I think what probably needs to happen is that we should look at the return type of a parameter of the collection rather than the generic type of the collection. I'll investigate further, thanks!

### CODE REVIEW

**Comment by kentongray** [comment]
OK I just created a work around, for some reason I have to use a named converter, if I try to just register a general purpose converter it does not work.

**Comment by matt-deboer** [comment]
Fix will be uploaded soon....

**Comment by kentongray** [comment]
Thanks Matt! Always impressed by your coding

**Comment by matt-deboer** [comment]
np.

please take a look now in the current master....let us know how that works
for you...

**Comment by kentongray** [comment]
Unfortunately I'm getting a really odd error now.. I can assure you that this class does exist. I'll see if I can rig up a test case on Monday, unless you have any ideas

````SEVERE: ma.glasnost.orika.impl.generator.CompilerStrategy$SourceCodeGenerationException: class com.iofficeconnect.space.Room is not accessible
ma.glasnost.orika.MappingException: ma.glasnost.orika.impl.generator.CompilerStrategy$SourceCodeGenerationException: class com.iofficeconnect.space.Room is not accessible
    at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:95)
    at ma.glasnost.orika.impl.DefaultMapperFactory.buildMapper(DefaultMapperFactory.java:1046)
    at ma.glasnost.orika.impl.DefaultMapperFactory.build(DefaultMapperFactory.java:910)
    at ma.glasnost.orika.impl.DefaultMapperFactory.getMapperFacade(DefaultMapperFactory.java:685)
...
Caused by: ma.glasnost.orika.impl.generator.CompilerStrategy$SourceCodeGenerationException: class com.iofficeconnect.space.Room is not accessible
    at ma.glasnost.orika.impl.generator.JavassistCompilerStrategy.assureTypeIsAccessible(JavassistCompilerStrategy.java:177)
    at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:55)
    ... 48 more
Caused by: javassist.NotFoundException: com.iofficeconnect.space.Room
    at javassist.ClassPool.get(ClassPool.java:436)
    at ma.glasnost.orika.impl.generator.JavassistCompilerStrategy.assureTypeIsAccessible(JavassistCompilerStrategy.java:175)
    ... 49 more

```
```

**Comment by matt-deboer** [comment]
is your Room class not public, by chance?

**Comment by kentongray** [comment]
I wish.. No everything is public and has a no args constructor, I'm
actually not sure why it is trying to map it. I'll try to spend more time
on it Monday and let you know what I see. It may very well be a config
error on my end. Thanks again

**Comment by kentongray** [comment]
Playing with it more I seem to have this issue with all classes (I remove one then the next class gets that same error). Debugging the code on the JavaassistCompilerStrategy I see the classPool only has primitive classes in it. Still investigating.

**Comment by matt-deboer** [comment]
is orika being loaded from a different classloader?

**Comment by kentongray** [comment]
Nope, same class loader, nothing tricky. I tried using the same build with
another mapping project that was working with a 1.2.5 Orika and it had the
same problem/exception (with other classes of course).

Kenton

**Comment by matt-deboer** [comment]
any other libraries involved which might change the current thread's context classloader?

**Comment by kentongray** [comment]
Both of these are running as a JAXWS servlet, but as far as I know nothing
that should cause any class loader oddities.

**Comment by kentongray** [comment]
For example before I call build I can successfully call/instantiate the
classes that are getting the errors immediately. Also I have hibernate
3.6.10 (which is what we've been using since I started using Orika), which
I know uses javaassist but nothing has changed lately.

**Comment by matt-deboer** [comment]
have you tried using the HibernateUnenhanceStrategy ?

call:
unenhanceStrategy(new HibernateUnenhanceStrategy())

on the DefaultMapperFactory.Builder....

**Comment by kentongray** [comment]
Yes I am using that.. FYI this happens when building (before mapping takes
place).

**Comment by elaatifi** [comment]
Did you use App Engine or JRebel ?

**Comment by kentongray** [comment]
@elaatifi no, just a plain ol' boring Tomcat. I'm really confused as to what is happening here. I can't map anything on my app, but if I do a test on the orika package it works fine. I had previously been using Orika without issue, so I'm wondering if something is wrong with my build...

 Matt, would it be possible for you to update your maven snapshot so I can try with your build?

**Comment by kentongray** [comment]
OK, I'm really so confused. So I simplified everything extremely, and was still getting the error. 

Then I just setup an entry point to test with the same libs/code and it worked. 

So that led me to believe there must be some conflict with Tomcat 6. I then created an incredibly simple war which just calls build with two internal classes and I had the same error. I really don't know what's up.... Any ideas? 

I tested this on old builds of 1.2, 1.3, and 1.3.5 and it worked, but the second I use 1.4-snapshot it stopped working.. There are quite a few commits on there, I don't even know where to start to blame..

If you want to give it a try here are links, 
Built WAR: https://dl.dropbox.com/u/64139279/orika.war
Source: https://dl.dropbox.com/u/64139279/OrikaWarTester.zip

Kenton

**Comment by matt-deboer** [comment]
I'll take a look..

**Comment by kentongray** [comment]
I wish you luck! I hope it breaks for you or else I'm going to feel even
crazier

**Comment by matt-deboer** [comment]
it looks like you're suggested change corrects the issue..it must have
something to do with the way web app containers often split web-inf/classes
and web-inf/lib into 2 separate class-loaders
anyway, I'll get that into the master in a few minutes here...

**Comment by matt-deboer** [comment]
give it a try now with the latest master...

**Comment by matt-deboer** [comment]
(sorry, the change was suggested by someone else, but anyway, it seems to
work)

**Comment by kentongray** [comment]
Worked great for me, thanks!

**Comment by mbrezovsky** [comment]
This topic help me! I've upgraded to the latest release and it works. Thanks.

**Comment by kentongray** [comment]
Closing old pull request

**Pull request closed without merging**
