### PR TITLE
Allow custom implementation of MapperFacade

### PR DESCRIPTION
**Pull request by papegaaij**
DefaultMapperFactory always creates a MapperFacadeImpl. It is possible to wrap this MapperFacade in a subclass by overriding getMapperFacade, but many method calls to MapperFacade are made from inside MapperFacadeImpl, making it impossible to intercept these method calls. With a custom MapperFacade (for example a subclass of MapperFacadeImpl), it is possible to intercept all calls, for example to wrap MappingStrategies.

This pull request contains a small patch to DefaultMapperFactory which makes it possible to build a custom MapperFacade. A minor issue is that the method is called from the constructor, when the instance variables of the factory are not yet initialized. IMHO it should be better to build these components in the builder, together with other components of the factory, but that would be a much bigger patch.

### CODE REVIEW

**Comment by papegaaij** [comment]
I don't know how to split pull requests, so this pull request now also contains the commits for #3

**Comment by elaatifi** [comment]
Dont worry about the split, 

It's OK for the first commit, I agree with you (this could be heavy lifting :+1:)
For the pooling example why not just use a custom ObjectFactory ?
Orika use custom object factories to create new instances (before starting copy) for a type instead you can just pull them from a pool.

Thanks

**Comment by papegaaij** [comment]
The pooling is a bit of manufactured example, because the full thing is too big to fit in a testcase. We use Orika to map beans coming into and being served by a REST api to JPA entities. These beans are annotated with instructions on how a bean should be mapped onto a JPA entity. These mapping instructions are added to the MappingContext at the root level and used at deeper levels. This can cause the same class to be mapped in different ways, depending on the context. We solved this by wrapping all MappingStrategies (that's why we need the first patch). With the second patch, we can return instances from the mapping strategy.

Btw, I don't think your solution with custom object factories will work. The generated code looks like this (shortened):

```
if (dest.getPooled() == null)
   dest.setPooled(mapper.map(source.getPooled(), context));
else
   mapper.map(source.getPooled(), dest.getPooled(), context);
```

No matter what you do in the second part of the mapping, it is impossible to change the 'pooled' property of 'dest'. The patch changes this code to:

```
if (dest.getPooled() == null)
   dest.setPooled(mapper.map(source.getPooled(), context));
else
   dest.setPooled(mapper.map(source.getPooled(), dest.getPooled(), context));
```

**Comment by papegaaij** [comment]
I just found a bug in my patch: map and mapReverse returned null rather than the previously mapped instance. This last commit fixes this.

**Comment by elaatifi** [comment]
Sorry for the late reply,
this could be shipped with next (bug fix) release ASAP.
Many thanks.

**Pull request merged**
